# Generated by Django 4.1.5 on 2023-04-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=20)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('state', models.TextField(choices=[('Maharashtra', 'Maharashtra')], default='Maharashtra')),
                ('city', models.TextField(choices=[('Mumbai', 'Mumbai')], default='Mumbai')),
                ('area', models.TextField(choices=[('Borivali(east)', 'Borivali(east)'), ('Borivali(West)', 'Borivali(west)'), ('Kandivali(east)', 'Kandivali(east)'), ('Kandivali(west)', 'Kandivali(west)'), ('Dahisar(east)', 'Dahisar(east)'), ('Dahisar(West)', 'Dahisar(west)'), ('Miraroad(east)', 'Miraroad(east)'), ('Miraroad(West)', 'Miraroad(west)'), ('Bhaindar(east)', 'Bhaindar(east)'), ('Bhaindar(West)', 'Bhaindar(west)'), ('Naigoan(east)', 'Naigoan(east)'), ('Naigoan(West)', 'Naigoan(west)'), ('Vasairoad(east)', 'Vasairoad(east)'), ('Vasairoad(West)', 'Vasairoad(west)'), ('Nalasopara(east)', 'Nalasopara(east)'), ('Nalasopara(West)', 'Nalasopara(west)'), ('Virar(east)', 'Virar(east)'), ('Virar(West)', 'Virar(west)')], default='Kandivali(East)')),
                ('pincode', models.TextField()),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Expired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.TextField()),
                ('category', models.TextField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Electronics', 'Electronics'), ('Clothes', 'Clothes')])),
                ('itemname', models.TextField()),
                ('discription', models.TextField()),
                ('key_features1', models.TextField()),
                ('key_features2', models.TextField()),
                ('key_features3', models.TextField()),
                ('key_features4', models.TextField()),
                ('old_itemprice', models.IntegerField()),
                ('new_itemprice', models.IntegerField()),
                ('percentage', models.IntegerField()),
                ('lastdate', models.DateField()),
                ('state', models.TextField()),
                ('city', models.TextField()),
                ('area', models.TextField()),
                ('address', models.TextField()),
                ('images', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Finalowner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=20)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.TextField()),
                ('state', models.TextField()),
                ('city', models.TextField()),
                ('area', models.TextField()),
                ('pincode', models.TextField()),
                ('images', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.TextField()),
                ('category', models.TextField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Electronics', 'Electronics'), ('Clothes', 'Clothes')])),
                ('itemname', models.TextField()),
                ('discription', models.TextField()),
                ('key_features1', models.TextField()),
                ('key_features2', models.TextField()),
                ('key_features3', models.TextField()),
                ('key_features4', models.TextField()),
                ('old_itemprice', models.IntegerField()),
                ('new_itemprice', models.IntegerField()),
                ('percentage', models.IntegerField()),
                ('lastdate', models.DateField()),
                ('state', models.TextField()),
                ('city', models.TextField()),
                ('area', models.TextField()),
                ('address', models.TextField()),
                ('images', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Order_placed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('sellername', models.TextField()),
                ('itemname', models.TextField()),
                ('paymentmode', models.TextField(choices=[('Online', 'Online'), ('cash on delievery', 'cash on delievery')], default='2')),
                ('piece', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=20)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.TextField()),
                ('state', models.TextField(choices=[('Maharashtra', 'Maharashtra')], default='Maharashtra')),
                ('city', models.TextField(choices=[('Mumbai', 'Mumbai')], default='Mumbai')),
                ('area', models.TextField(choices=[('Borivali(east)', 'Borivali(east)'), ('Borivali(West)', 'Borivali(west)'), ('Kandivali(east)', 'Kandivali(east)'), ('Kandivali(west)', 'Kandivali(west)'), ('Dahisar(east)', 'Dahisar(east)'), ('Dahisar(West)', 'Dahisar(west)'), ('Miraroad(east)', 'Miraroad(east)'), ('Miraroad(West)', 'Miraroad(west)'), ('Bhaindar(east)', 'Bhaindar(east)'), ('Bhaindar(West)', 'Bhaindar(west)'), ('Naigoan(east)', 'Naigoan(east)'), ('Naigoan(West)', 'Naigoan(west)'), ('Vasairoad(east)', 'Vasairoad(east)'), ('Vasairoad(West)', 'Vasairoad(west)'), ('Nalasopara(east)', 'Nalasopara(east)'), ('Nalasopara(West)', 'Nalasopara(west)'), ('Virar(east)', 'Virar(east)'), ('Virar(West)', 'Virar(west)')], default='Kandivali(East)')),
                ('pincode', models.TextField()),
                ('images1', models.FileField(default=0, upload_to='images/')),
                ('images2', models.FileField(default=0, upload_to='images/')),
                ('images3', models.FileField(default=0, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('seller', models.TextField()),
                ('category', models.TextField()),
                ('itemname', models.TextField()),
                ('old_itemprice', models.IntegerField(default=0)),
                ('new_itemprice', models.IntegerField(default=0)),
                ('lastdate', models.TextField(null=True)),
            ],
        ),
    ]
