# Generated by Django 4.1.5 on 2023-04-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Save',
        ),
    ]
