# Generated by Django 4.1.5 on 2023-04-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_delete_save'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('seller', models.TextField()),
                ('category', models.TextField()),
                ('itemname', models.TextField()),
                ('old_itemprice', models.IntegerField(default=0)),
                ('new_itemprice', models.IntegerField(default=0)),
                ('lastdate', models.TextField(null=True)),
            ],
        ),
    ]
