# Generated by Django 4.1.5 on 2023-04-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_save'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final_order_placed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('sellername', models.TextField()),
                ('itemname', models.TextField()),
                ('paymentmode', models.TextField(choices=[('Online', 'Online'), ('cash on delievery', 'cash on delievery')], default='2')),
                ('piece', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
