# Generated by Django 4.1.3 on 2023-01-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='image',
            new_name='images',
        ),
    ]
