# Generated by Django 4.1.5 on 2023-02-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_rename_image_owner_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finalowner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('images', models.ImageField(upload_to='images')),
            ],
        ),
    ]
