# Generated by Django 4.1.5 on 2023-02-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_finalowner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
