# Generated by Django 4.1.5 on 2023-02-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0011_item_category_alter_item_itemprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='lastdate',
            field=models.DateField(),
        ),
    ]
