# Generated by Django 4.1.5 on 2023-02-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0012_alter_item_lastdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
