# Generated by Django 4.1.5 on 2023-02-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0013_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.TextField()),
                ('category', models.TextField()),
                ('itemname', models.TextField()),
                ('itemprice', models.IntegerField()),
                ('lastdate', models.DateField()),
                ('images', models.ImageField(upload_to='images')),
            ],
        ),
    ]
