# Generated by Django 4.1.5 on 2023-02-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0014_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalowner',
            name='images',
            field=models.ImageField(upload_to='static/finalimages'),
        ),
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.ImageField(upload_to='static/prodimages'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='images',
            field=models.ImageField(upload_to='static/tempimages'),
        ),
    ]
