# Generated by Django 4.1.5 on 2023-02-18 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0019_alter_finalowner_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='images',
        ),
    ]
