# Generated by Django 4.1.5 on 2023-02-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0020_remove_item_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
    ]
