# Generated by Django 4.1.5 on 2023-02-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0021_item_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='images',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='images'),
        ),
    ]
