# Generated by Django 4.1.5 on 2023-02-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0022_alter_owner_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='images',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
