# Generated by Django 4.1.5 on 2023-02-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0024_alter_owner_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalowner',
            name='images',
            field=models.ImageField(upload_to='static'),
        ),
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.ImageField(upload_to='static'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='images',
            field=models.ImageField(upload_to='static'),
        ),
    ]
