# Generated by Django 4.1.5 on 2023-02-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0025_alter_finalowner_images_alter_item_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='images',
            field=models.ImageField(upload_to='static/%y'),
        ),
    ]
