# Generated by Django 4.1.5 on 2023-02-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0027_alter_finalowner_images_alter_item_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.TextField(choices=[('1', 'Vegetables'), ('2', 'Fruits'), ('3', 'Electronics'), ('4', 'Clothes')], default='1'),
        ),
    ]
